apiVersion: tomcat.apache.org/v1alpha1
kind: Tomcat
metadata:
  name: tomcatdemo
spec:
  applicationName: tomcat-demo
  applicationImage: docker.io/jfclere/tomcat-demo:latest
  webArchiveImage: docker.io/jfclere/tomcat-maven:latest
  webAppURL: https://github.com/jfclere/demo-webapp.git
  size: 3
