apiVersion: v1
kind: Service
metadata:
  name: tomcat-balancer
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    WebServer: tomcatdemo
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
