apiVersion: v1
kind: Service
metadata:
  labels:
    WebServer: tomcatdemo
    deploymentConfig: tomcat-demo
  name: tomcat-balancer
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: tomcat-demo
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
