apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
    - name: task-pv-container
      image: quay.io/jfclere/tomcat10
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/deployments/webapps"
          name: task-pv-storage
